services:
  gemini-live-to-openai-adapter:
    container_name: gemini-live-to-openai-adapter
    build:
      context: ./
      dockerfile: Dockerfile
    read_only: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    ports:
      - '3000:3000'